baseURL = "https://notes.architectureterminal.com"
languageCode = 'en-us'
title = "From Code to Influence: A Software Engineerâ€™s Journey"
copyright = "Srikanth Doddi"
theme = 'ananke'

[taxonomies]
  category = "categories"
  tag = "tags"

[pagination]
  pagerSize = 10000

[markup.goldmark.renderer]
  unsafe= true

[params]
  recent_posts_number = 10000
  images = ["/static/author.png"]
  custom_css = ["/static/pygments.css"]
  background_color_class = 'bg-white'
  body_classes = "avenir bg-white"
  [params.banner]
    enabled = false
    bg_color = 'bg-washed-yellow'
  [params.Author]
    name = "Srikanth Doddi"
[menu]
  [[menu.main]]
    weight = 700
    name = "Guides"
    url = "/guides/"
